### ISSUE TITLE
[Bug]: useActionData cannot be mocked

### ISSUE THREAD

**Issue by cjoecker** [airjp73/remix-validated-form#317]
### Which packages are impacted?

- [X] `remix-validated-form`
- [X] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

`remox-validated-form`: 5.0.2

### Please provide a link to a minimal reproduction of the issue.

https://codesandbox.io/p/sandbox/react-typescript-forked-vzq65s?file=%2Fsrc%2FApp.test.tsx%3A14%2C24

### Steps to Reproduce the Bug or Issue

1. Create a unit test with `vitest` and `testing-library`
2. Add `ValidatedForm` to a component and render it in a test
3. Mock `useActionData`

### Expected behavior

`useActionData` is moked and the error `useActionData must be used within a data router` is not shown

### Additional context

I know that `useActionData` is mocked because in the `mockImplementation` I'm logging something that is shown in the console of the test because I also use the hook in the `Demo` component. 
But `ValidatedForm` is not using the mock and I still don't know why.

**Comment by airjp73** [comment]
It sounds like you might need to inline the dependency to get this to work like that. ([reference](https://github.com/vitest-dev/vitest/issues/1336)). Have you tried that?

**Comment by cjoecker** [comment]
@airjp73 good point! But after adding the inline dependency configuration, it is still not working. I open an [issue](https://github.com/vitest-dev/vitest/issues/3936) in vitest to see if it is coming from the library.

**Comment by madmax141** [comment]
any luck @cjoecker ? I also looked into rendering validated form in a remix stub (an experimental testing utility for remix seen used here https://github.com/remix-run/remix/blob/dev/packages/remix-testing/__tests__/stub-test.tsx) but that also didn't work unfortunately

**Comment by cjoecker** [comment]
@madmax141 nope. Also still no answer in the `Vitest` issue :(

**Comment by chohner** [comment]
Looks like we are seeing this newly in [our E2E tests](https://github.com/digitalservicebund/a2j-rechtsantragstelle/actions/runs/6275872562/job/17044368079?pr=309) after updating to Remix v2 and remix-validated-forms 5.1.3

**Comment by airjp73** [comment]
It seems this error is happening in actual apps too, not just in vitest. It's looking like it's a dependency resolution problem where RVF is pulling in a different version of remix from the rest of the app.

**Comment by airjp73** [comment]
This should be fixed now in 5.1.5.

**Comment by cjoecker** [comment]
@airjp73 I updated all dependencies in the [codesandbox](https://codesandbox.io/p/sandbox/react-typescript-forked-vzq65s?file=%2Fsrc%2FApp.test.tsx%3A14%2C24) but I still get the same error 😭

**Comment by cjoecker** [comment]
I got [this](https://github.com/vitest-dev/vitest/issues/3936#issuecomment-1739836844) answer from the `vitest` maintainer but I still didn't manage to make it work. Feel free to give it a try.

**Comment by cjoecker** [comment]
As a workaround for the people still struggling with this, I'm using now the [createRemixStub](https://remix.run/docs/en/main/other-api/testing) for mocking the `useLoaderData` and it is working fine.

**Comment by airjp73** [comment]
RVF v6 has been released 🎉 

This should hopefully be addressed in that version. If it's still a problem after upgrading, please feel free to open a new issue.

You can find the documentation [here](https://rvf-js.io) and the migration guide [here](https://rvf-js.io/migration).
